set(target MythicRuntime)

set(RUNTIME_PUBLIC_INCLUDE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Public)
set(RUNTIME_PRIVATE_INCLUDE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Private)

set(WINDOWS_SOURCES_FILES
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Windows/System.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Windows/System.cpp
)

set(MEMORY_SOURCES_FILES
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Memory/MimallocHelper.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Memory/MallocHelper.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Memory/MallocHelper.cpp
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Memory/MimallocHelper.cpp
)

set(LOG_SOURCES_FILES
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Log/QuillLoggerHelper.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Log/LogManager.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Log/Loggers.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Log/QuillLoggerHelper.cpp
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Log/LogManager.cpp
)

set(SYSTEM_SOURCES_FILES
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/System/SystemHelper.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/System/SystemHelper.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/System/SystemEnumerations.h
)

set(PARALLEL_SOURCES_FILES
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Parallel/CpuMaskHelper.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Parallel/CpuMaskHelper.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Parallel/ThreadHelper.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Parallel/ThreadHelper.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Parallel/ThreadPool.h
)

set(RUNTIME_CORE_SOURCES
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/MythicRuntime.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/MythicRuntime.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Config.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/CoreRuntime.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/CoreRuntime.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/StaticString.h
)

add_library(${target} SHARED
	${RUNTIME_CORE_SOURCES}
	${PARALLEL_SOURCES_FILES}
	${SYSTEM_SOURCES_FILES}
	${LOG_SOURCES_FILES}
	${MEMORY_SOURCES_FILES}
	${WINDOWS_SOURCES_FILES}
)

target_link_libraries(${target} PRIVATE 
						quill
)

target_link_libraries(${target} PUBLIC
						mimalloc
)

target_include_directories(${target} PRIVATE 
						   ${CMAKE_CURRENT_SOURCE_DIR}/Public
						   ${CMAKE_CURRENT_SOURCE_DIR}/Private
)

target_compile_definitions(${target} PRIVATE
						   RUNTIME_EXPORT
)