set(target MythicRuntime)

set(RUNTIME_PUBLIC_INCLUDE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Public)
set(RUNTIME_PRIVATE_INCLUDE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Private)

add_library(${target} SHARED
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/MythicRuntime.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/MythicRuntime.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Config.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/CpuMaskHelper.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/CpuMaskHelper.cpp
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/CoreRuntime.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/CoreRuntime.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/SystemHelper.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/StaticString.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/Windows/System.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/SystemHelper.cpp
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/Windows/System.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/MallocHelper.h
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/ThreadHelper.h
	${RUNTIME_PRIVATE_INCLUDE_DIRECTORY}/ThreadHelper.cpp
	${RUNTIME_PUBLIC_INCLUDE_DIRECTORY}/QuillLoggerHelper.h
)

target_link_libraries(${target} PRIVATE 
						quill
)

target_link_libraries(${target} PUBLIC
						mimalloc
)

target_include_directories(${target} PRIVATE 
						   ${CMAKE_CURRENT_SOURCE_DIR}/Public
						   ${CMAKE_CURRENT_SOURCE_DIR}/Private
)

target_compile_definitions(${target} PRIVATE
						   RUNTIME_EXPORT
)